###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /usr/share/nginx
        volumes:
            - '.docker/dbdata:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=docker
            - MYSQL_DATABASE=JN2
            - MYSQL_USER=docker
            - MYSQL_PASSWORD=docker
        ports:
            - '8002:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /usr/share/nginx
        volumes:
            - '.:/usr/share/nginx'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /usr/share/nginx
        volumes:
            - '.:/usr/share/nginx'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'

